<?php

namespace APOSite\Models;

use APOSite\Http\Transformers\ServiceEventTransformer;

class ServiceEvent extends BaseModel
{
    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes); // TODO: Change the autogenerated stub
        $transformer = new ServiceEventTransformer();
    }


    protected $fillable = [
        'service_type',
        'location',
        'project_type',
        'off_campus',
        'travel_time'
    ];

    public $transformer;

}
